export const BEGIN = 'BEGIN'
export const SERIES_SUCCESS = 'SERIES SUCCESS'
export const MOVIES_SUCCESS = 'MOVIES SUCCESS'
export const ERROR = 'ERROR'
export const FILTER_SET = 'FILTER_SET'
export const FILTER = 'FILTER'
export const SORT_YEAR = 'SORT YEAR'
export const SORT_TITLE = 'SORT TITLE'
